package ru.flashrainbow.gameofthrones.data.storage.models;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Characters".
*/
public class CharacterDao extends AbstractDao<Character, Long> {

    public static final String TABLENAME = "Characters";

    /**
     * Properties of entity Character.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Gender = new Property(3, String.class, "gender", false, "GENDER");
        public final static Property Culture = new Property(4, String.class, "culture", false, "CULTURE");
        public final static Property Born = new Property(5, String.class, "born", false, "BORN");
        public final static Property Died = new Property(6, String.class, "died", false, "DIED");
        public final static Property Title = new Property(7, String.class, "title", false, "TITLE");
        public final static Property Aliases = new Property(8, String.class, "aliases", false, "ALIASES");
        public final static Property Father = new Property(9, String.class, "father", false, "FATHER");
        public final static Property Mother = new Property(10, String.class, "mother", false, "MOTHER");
        public final static Property Allegiances = new Property(11, String.class, "allegiances", false, "ALLEGIANCES");
        public final static Property TvSeries = new Property(12, String.class, "tvSeries", false, "TV_SERIES");
    }

    private DaoSession daoSession;


    public CharacterDao(DaoConfig config) {
        super(config);
    }
    
    public CharacterDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"Characters\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"URL\" TEXT NOT NULL UNIQUE ," + // 1: url
                "\"NAME\" TEXT NOT NULL ," + // 2: name
                "\"GENDER\" TEXT," + // 3: gender
                "\"CULTURE\" TEXT," + // 4: culture
                "\"BORN\" TEXT," + // 5: born
                "\"DIED\" TEXT," + // 6: died
                "\"TITLE\" TEXT," + // 7: title
                "\"ALIASES\" TEXT," + // 8: aliases
                "\"FATHER\" TEXT," + // 9: father
                "\"MOTHER\" TEXT," + // 10: mother
                "\"ALLEGIANCES\" TEXT," + // 11: allegiances
                "\"TV_SERIES\" TEXT);"); // 12: tvSeries
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"Characters\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Character entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUrl());
        stmt.bindString(3, entity.getName());
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(4, gender);
        }
 
        String culture = entity.getCulture();
        if (culture != null) {
            stmt.bindString(5, culture);
        }
 
        String born = entity.getBorn();
        if (born != null) {
            stmt.bindString(6, born);
        }
 
        String died = entity.getDied();
        if (died != null) {
            stmt.bindString(7, died);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(8, title);
        }
 
        String aliases = entity.getAliases();
        if (aliases != null) {
            stmt.bindString(9, aliases);
        }
 
        String father = entity.getFather();
        if (father != null) {
            stmt.bindString(10, father);
        }
 
        String mother = entity.getMother();
        if (mother != null) {
            stmt.bindString(11, mother);
        }
 
        String allegiances = entity.getAllegiances();
        if (allegiances != null) {
            stmt.bindString(12, allegiances);
        }
 
        String tvSeries = entity.getTvSeries();
        if (tvSeries != null) {
            stmt.bindString(13, tvSeries);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Character entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUrl());
        stmt.bindString(3, entity.getName());
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(4, gender);
        }
 
        String culture = entity.getCulture();
        if (culture != null) {
            stmt.bindString(5, culture);
        }
 
        String born = entity.getBorn();
        if (born != null) {
            stmt.bindString(6, born);
        }
 
        String died = entity.getDied();
        if (died != null) {
            stmt.bindString(7, died);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(8, title);
        }
 
        String aliases = entity.getAliases();
        if (aliases != null) {
            stmt.bindString(9, aliases);
        }
 
        String father = entity.getFather();
        if (father != null) {
            stmt.bindString(10, father);
        }
 
        String mother = entity.getMother();
        if (mother != null) {
            stmt.bindString(11, mother);
        }
 
        String allegiances = entity.getAllegiances();
        if (allegiances != null) {
            stmt.bindString(12, allegiances);
        }
 
        String tvSeries = entity.getTvSeries();
        if (tvSeries != null) {
            stmt.bindString(13, tvSeries);
        }
    }

    @Override
    protected final void attachEntity(Character entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Character readEntity(Cursor cursor, int offset) {
        Character entity = new Character( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // url
            cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // gender
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // culture
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // born
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // died
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // title
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // aliases
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // father
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // mother
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // allegiances
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // tvSeries
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Character entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrl(cursor.getString(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setGender(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCulture(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBorn(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDied(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTitle(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAliases(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFather(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setMother(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setAllegiances(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTvSeries(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Character entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Character entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Character entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
